SELECT contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5, COUNT(*) as x
FROM collisions_2015
WHERE cyclist_injured > 0 or cyclist_killed > 0 AND borough='BROOKLYN' 
GROUP BY contributing_factor_vehicle_1,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5
ORDER BY x DESC;
